### ISSUE TITLE
Crash When Selecting Output Device

### ISSUE THREAD

**Issue by scyto** [nicojeske/MasterVolumeSync#2]
Was working fine on win11, survived weekly pre-release build to build upgrades ok.

On Win11 25140.rs_prerelease it now crashes when i select anything in the the output device section of the menu, selecting the what you hear device doesn't crash app. 

1. could be just intermittent build issue (e.g. might be fixed in this weeks build.
2. could be change in way audio devices are specified 
3. could be an artefact of build to build upgrade (maybe breaking dot net)?

i am not a programmer so not sure... just my theses...

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MasterVolumeSync.Worker.uncheckOldAndCheckNewItem(Object sender, ToolStripMenuItem previousItem) in H:\01-Projects\Random\MasterVolumeSync\MasterVolumeSync\Worker.cs:line 152
   at MasterVolumeSync.Worker.SelectOutputDevice(Object sender, EventArgs e) in H:\01-Projects\Random\MasterVolumeSync\MasterVolumeSync\Worker.cs:line 131
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.CoreLib.dll
----------------------------------------
MasterVolumeSync
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/MasterVolumeSync.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.dll
----------------------------------------
Microsoft.Extensions.Hosting.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Hosting.Abstractions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/netstandard.dll
----------------------------------------
Microsoft.Extensions.Hosting
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Hosting.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.DependencyInjection.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Configuration.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.Abstractions.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.dll
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.DependencyInjection.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.dll
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Logging.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.Tracing.dll
----------------------------------------
Microsoft.Extensions.Configuration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.dll
----------------------------------------
Microsoft.Extensions.Configuration.EnvironmentVariables
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.EnvironmentVariables.dll
----------------------------------------
Microsoft.Extensions.Configuration.CommandLine
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.CommandLine.dll
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Primitives.dll
----------------------------------------
Microsoft.Extensions.FileProviders.Physical
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.FileProviders.Physical.dll
----------------------------------------
Microsoft.Extensions.FileProviders.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.FileProviders.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Configuration.FileExtensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.FileExtensions.dll
----------------------------------------
Microsoft.Extensions.Configuration.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.Json.dll
----------------------------------------
Microsoft.Extensions.Configuration.UserSecrets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.UserSecrets.dll
----------------------------------------
Microsoft.Extensions.Configuration.Binder
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Configuration.Binder.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Linq.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.IO.FileSystem.Watcher.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.Primitives.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Concurrent.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Memory.dll
----------------------------------------
Microsoft.Extensions.FileSystemGlobbing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.FileSystemGlobbing.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.Overlapped.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Text.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Text.Json.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
Microsoft.Extensions.Options
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Options.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
Microsoft.Extensions.Logging.Configuration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Logging.Configuration.dll
----------------------------------------
Microsoft.Extensions.Logging.Debug
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Logging.Debug.dll
----------------------------------------
Microsoft.Extensions.Logging.EventSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Logging.EventSource.dll
----------------------------------------
Microsoft.Extensions.Logging.EventLog
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Logging.EventLog.dll
----------------------------------------
Microsoft.Extensions.Logging.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Logging.Console.dll
----------------------------------------
Microsoft.Extensions.Options.ConfigurationExtensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.222.5408
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/Microsoft.Extensions.Options.ConfigurationExtensions.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Threading.Thread.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Console
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Console.dll
----------------------------------------
System.Diagnostics.EventLog
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Diagnostics.EventLog.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Specialized.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.InteropServices.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Private.Uri.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.Intrinsics.dll
----------------------------------------
NAudio.Wasapi
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Nico%20Jeske%20IT/MasterVolumeSync/NAudio.Wasapi.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.422.16407
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.422.16407
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/System.Drawing.Common.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Drawing.Primitives.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.422.16404
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.422.16407
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.5/Accessibility.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.522.21309
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.5/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

```

**Comment by scyto** [comment]
i looked at code, i do note that it can't unselect existing item, because there appears to not be one in the menu....

![image](https://user-images.githubusercontent.com/11369180/174653441-69af239f-e286-4ffc-9094-a2b5ef043548.png)

**Comment by scyto** [comment]
I am also unclear where the app saves it settings to?  The settings json in the app folder don't get modified and i can't quite parse https://github.com/nicojeske/MasterVolumeSync/blob/master/MasterVolumeSync/SettingsManager.cs to understand the file name it uses (sorry not a programmer).

**Comment by nicojeske** [comment]
You will find the settings.json in C:\Users\yourusername\AppData\Local\MasterVolumeSync. 

You could try to manually update the settings.json.

I would first try to set the value of OutputId to an empty string and then restarting the app.
```json
{"OutputId":"","WhatUHearId":"do not change this value"}
```

If this won't help you could try to manually set the value of OutputId to your device id. You can find the device identifier by opening the device manager on windows, open audio inputs and outputs, rightclick on your output device, properties, details and select the device instance path property. You will need the value starting with "{0.0...".

**Comment by scyto** [comment]
> I would first try to set the value of OutputId to an empty string and then restarting the app.

Worked perfectly.

Also I looked for the file in that location before I posted - gosh i am blind today, lol, thanks! 

i guess the device ID changed between upgrades or somesuch, i should have saved the file before i edited it, as then i could have compared, doh

**Comment by nicojeske** [comment]
Perfect, I am glad I could help!

**Comment by scyto** [comment]
Thanks, to you for making this tool too - i literally have been looking for something like this for a decade since MS changed the audio subsystem by not letting master volume control encoded streams on any hardware.  I will let you know if it happens again - hopefully this is a one off with no need to consider some error handling.  If there is a next time i will carefully collect device IDs before editing the file.

**Comment by scyto** [comment]
FYI I hit this again today (firs time since june 20), same fixed worked.

The output ID for the same device changed from
{0.0.0.00000000}.{a0f86a7a-35f8-41d7-94b1-cf8126e79833}
to
{0.0.0.00000000}.{c426e238-4004-41c1-84a8-8e28317af6ae}

this happened because of one of these:

- windows to windows update (unlikely as i do one of those a week because i am insider)
- i reinstalled sound blaster command and driver (my guess is it was this one, but ¯\(°_o)/¯ )

I suspect there are only a few of us using this so i don't think you need to have an error handling case as its easy fixed by editing the json file.
