### ISSUE TITLE
App Startup crash (x64)

### ISSUE THREAD

**Issue by alperozisik** [nicojeske/MasterVolumeSync#7]
Hi,
When I have tried to run the app, it seems not to start at all.
After some tests, I was not able to find it. Afterwards, I cloned the repo and started to debug.
The built app is also crashing. I googled the error; it seems that is related to **build target** of the project.
I changed the Project Settings > Build > General > Platform Target = x86 and rebuild. After that the app is running fine.
I believe, rest of the x64 platforms are suffering from this.
If you change this and make a new release it will be fine.
If you do not have a x64 system, we can collaborate on this.

My system:
- Windows 11
- Soundblaster Zx

I think it is possible add Soundblaster Z series in the tested / supported cards.

**Comment by nicojeske** [comment]
Hi there,

I switched to a new installer format and in the process the software is now building trageting AnyCPU.

Could you try the newly released version [1.0.8](https://github.com/nicojeske/MasterVolumeSync/releases/tag/v1.0.8)?

**Comment by alperozisik** [comment]
I have tested it and for the exe it behaves the same - it crashes.
You should be setting the Platform Target as x86. It is based on the third party libraries that you are using.

**Comment by alperozisik** [comment]
Also, I have noticed that you have included SoundBlaster Zx in the supported list. Correct writing would be: `Sound Blaster Z/Zx` _(confirmed on the creative website)_. The only difference between Z and Zx is the external microphone and headset dongle. Internally it is using the exactly the same PCIe card. Their drivers are also same.

**Comment by nicojeske** [comment]
I've just adjusted the pipeline to also build targeting x86. If this won't help there is unfortunately not that much that I can do, as I am not able to reproduce this issue. 

Could you perhaps share the error message if the problem is not solved?

**Comment by alperozisik** [comment]
Here is the case

![NVIDIA_Share_456j3arINO](https://github.com/nicojeske/MasterVolumeSync/assets/7248325/5cfd07f9-9938-406e-861e-458eae9798f9)

Error:
```
System.BadImageFormatException
  HResult=0x800700C1
  Message=Could not load file or assembly 'System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Format of the executable (.exe) or library (.dll) is invalid.
  Source=MasterVolumeSync
  StackTrace:
   at MasterVolumeSync.Worker.ShowTrayIcon() in C:\Users\alper\source\repos\alperozisik\MasterVolumeSync\MasterVolumeSync\Worker.cs:line 96
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 106

```

**Comment by alperozisik** [comment]
I have created a pull request #8

**Comment by nicojeske** [comment]
The project works as it is on hundreds of devices. I see no need to change the build mode.
